stages:
  download_dataset:
    cmd: python equipo35_mlops/stages/download_data.py
    deps:
      - equipo35_mlops/stages/download_data.py
    outs:
      - ${shared.raw_data_path}/${shared.raw_file_name}
  preprocess_data:
    cmd: python equipo35_mlops/stages/preprocessing.py
    deps:
      - equipo35_mlops/stages/preprocessing.py
      - ${shared.raw_data_path}/${shared.raw_file_name}
    outs:
      - ${shared.processed_data_path}/X_train.npy
      - ${shared.processed_data_path}/X_test.csv
      - ${shared.processed_data_path}/y_train.npy
      - ${shared.processed_data_path}/y_test.npy
      - ${shared.models_path}/preprocessor.pkl
  train_model:
    cmd: python equipo35_mlops/stages/training.py
    deps:
      - equipo35_mlops/stages/training.py
      - ${shared.processed_data_path}/X_train.npy
      - ${shared.processed_data_path}/y_train.npy
      - ${shared.models_path}/preprocessor.pkl
    outs:
      - ${shared.models_path}/logistic_regression.pkl
  evaluate_model:
    cmd: python equipo35_mlops/stages/evaluation.py
    deps:
      - equipo35_mlops/stages/evaluation.py
      - ${shared.models_path}/preprocessor.pkl
      - ${shared.models_path}/logistic_regression.pkl