stages:
  download_dataset:
    cmd: python equipo35_mlops/main.py download-dataset
    outs:
      - ${shared.rawdata_path}/${shared.raw_file_name}
  preprocess_data:
    cmd: python equipo35_mlops/main.py preprocess
    deps:
      - equipo35_mlops/modeling/student_performance.py
      - ${shared.rawdata_path}/${shared.raw_file_name}
    outs:
      - ${shared.processed_data_path}/X_train.npy
      - ${shared.processed_data_path}/X_test.npy
      - ${shared.processed_data_path}/y_train.npy
      - ${shared.processed_data_path}/y_test.npy
      - ${shared.models_path}/preprocessor.pkl
  train_model:
    cmd: python equipo35_mlops/main.py training
    deps:
      - equipo35_mlops/modeling/student_performance.py
      - ${shared.processed_data_path}/X_train.npy
      - ${shared.processed_data_path}/y_train.npy
      - ${shared.models_path}/preprocessor.pkl
    outs:
      - ${shared.models_path}/logistic_regression.pkl
      - ${shared.models_path}/random_forest.pkl
      - ${shared.models_path}/svm.pkl
      - ${shared.models_path}/xgboost.pkl