shared:
  raw_data_path: 'data/raw'
  raw_file_name: 'student_data_df.csv'
  processed_data_path: 'data/processed'
  models_path: 'models'

target_model: 'logistic_regression'
mlflow_server_uri: 'https://mlflow.dantumlogic.com'

models:
  logistic_regression:
    C: 10
    random_state: 42
    solver: 'lbfgs'
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 10
  svm:
    C: 1
    kernel: 'rbf'
  xgboost:
    n_estimators: 100
    max_depth: 7
    learning_rate: 0.02

